### ISSUE TITLE
Unexpected crash near the end of generating.

### ISSUE THREAD

**Issue by Michael1999US** [pop4959/Chunky#153]
### Hi,
Can you check this hr_err log?

I tried to pre-generate my world, but it crashes when it's near 100%.
After that your plugin reset to default value (world world, shape square, center  0 0, radius 500),
chunky won't generate my world without further crashes.

**Lists of plugins:** 

> ATopPlayers, BetterPortals, BKCommonLib, BlockProt, BlueMap, ChestSort, Chunky, Crawling, FarmProtect*, Graves, GSit, HiveChecker, IllegalStack, InventoryRollbackPlus, InvSeePlusPlus, KeepChunks, LightAPI, LuckPerms, NotTooExpensive, PL-Hide, PlaceholderAPI, Plan, PlayTime*, PlugManX (PlugMan), ProtocolLib, Redye, ReviveMe, ServerlistMOTD*, SkinsRestorer, sleep-most, StackMob, SuperVanish, Themis, Tweakin, UltimateServerProtector*, UltimateTimber, UnstripLog.

Let me know if you need anything further.

Lists of logs:
[hs_err_pid43.log](https://github.com/pop4959/Chunky/files/7725636/hs_err_pid43.log)
[hs_err_pid44.log](https://github.com/pop4959/Chunky/files/7725637/hs_err_pid44.log)

**Comment by Michael1999US** [comment]
Also sometimes i get:
```
Failed to read chunk data for task: Task for world: 'world' at -397,125 poi: false, hash: 1404045953
net.minecraft.ReportedException: Loading NBT data
        at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:504) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:44) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:31) ~[?:?]
        at net.minecraft.nbt.ListTag$1.load(ListTag.java:33) ~[?:?]
        at net.minecraft.nbt.ListTag$1.b(ListTag.java:16) ~[?:?]
        at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:498) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:44) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:31) ~[?:?]
        at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:243) ~[?:?]
        at net.minecraft.nbt.NbtIo.read(NbtIo.java:188) ~[?:?]
        at net.minecraft.nbt.NbtIo.read(NbtIo.java:178) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:208) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:187) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkStorage.read(ChunkStorage.java:146) ~[?:?]
        at net.minecraft.server.level.ChunkMap.f(ChunkMap.java:1655) ~[paper-1.18.1.jar:git-Paper-77]
        at net.minecraft.server.level.ServerLevel$2.readData(ServerLevel.java:360) ~[?:?]
        at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) ~[paper-1.18.1.jar:git-Paper-77]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-77]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-77]
Caused by: java.util.zip.ZipException: incorrect data check
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[?:?]
        at net.minecraft.util.FastBufferedInputStream.read(FastBufferedInputStream.java:45) ~[paper-1.18.1.jar:git-Paper-77]
        at java.io.DataInputStream.readFully(DataInputStream.java:201) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
        at net.minecraft.nbt.CompoundTag.readNamedTagName(CompoundTag.java:493) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:42) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:31) ~[?:?]
        at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:498) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:44) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:31) ~[?:?]
        at net.minecraft.nbt.ListTag$1.load(ListTag.java:33) ~[?:?]
        at net.minecraft.nbt.ListTag$1.b(ListTag.java:16) ~[?:?]
        at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:498) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:44) ~[?:?]
        at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:31) ~[?:?]
        at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:243) ~[?:?]
        at net.minecraft.nbt.NbtIo.read(NbtIo.java:188) ~[?:?]
        at net.minecraft.nbt.NbtIo.read(NbtIo.java:178) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:208) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:187) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkStorage.read(ChunkStorage.java:146) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.f(ChunkTracker.java:1655) ~[?:?]
        ... 4 more
```

**Comment by pop4959** [comment]
That error typically means you have chunk corruption in your world. This is normally something that would have already occurred before using chunky, but might not have been noticeable since those chunks weren't being loaded. Delete those chunks or restore from a safe backup. If you're still having trouble, please join the [Discord](https://discord.gg/ZwVJukcNQG) support channel and someone might be able to give you further advice.
