### ISSUE TITLE
throw error when fill the world

### ISSUE THREAD

**Issue by gundami** [pop4959/Chunky#158]
```
[14:33:44 ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (-2304,-448), hashcode:484202926, priority: -1
java.lang.NullPointerException: null
```
or
```[14:38:11 ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (-2304,98), hashcode:1857975488, priority: -1
java.lang.NullPointerException: Cannot invoke "ca.spottedleaf.dataconverter.types.MapType.hasKey(Object)" because "level" is null
        at ca.spottedleaf.dataconverter.minecraft.versions.V2842$1.convert(V2842.java:25) ~[paper-1.18.1.jar:git-Paper-101]
        at ca.spottedleaf.dataconverter.minecraft.versions.V2842$1.convert(V2842.java:17) ~[paper-1.18.1.jar:git-Paper-101]
        at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:79) ~[paper-1.18.1.jar:git-Paper-101]
        at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.18.1.jar:git-Paper-101]
        at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:79) ~[paper-1.18.1.jar:git-Paper-101]
        at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:40) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:115) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[paper-1.18.1.jar:git-Paper-101]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-101]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-101]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-101]
```
console throw lots of error like this.
using paper-1.18.1-101, Chunky-1.2.153 and ChunkyBorder-1.0.59.jar

**Comment by pop4959** [comment]
This is not an error with Chunky, but you either have corrupt chunks in your world or there is a bug with [DataConverter](https://github.com/PaperMC/DataConverter) (Paper's DFU replacement). Report the error there if you are absolutely sure that your world is fine (I would recommend trying from a backup first).

**Comment by pop4959** [comment]
I forgot to comment sooner but this was confirmed to be an issue in Paper, and was fixed recently. If anyone is having this issue, be sure to update.
