### ISSUE TITLE
NullPointerException: Cannot invoke "org.popcraft.chunky.Chunky.disable()" because "this.chunky" is null

### ISSUE THREAD

**Issue by valkyrienyanko** [pop4959/Chunky#222]
MC Ver 1.18.2
Modpack: The Energy Race v7 (https://www.curseforge.com/minecraft/modpacks/the-energy-race)

Created a brand new world / server. As soon as I joined, this error appeared crashing the server.

```
[17:06:31] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "org.popcraft.chunky.Chunky.disable()" because "this.chunky" is null
        at org.popcraft.chunky.ChunkyFabric.lambda$onInitialize$2(ChunkyFabric.java:42) ~[Chunky-1.2.164.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.1.0+cc71601c60-45cc2ee6a8b6b174.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bip000$beforeShutdownServer(MinecraftServer.java:5317) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:565) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:729) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by pop4959** [comment]
Can you post the full error log, this error doesn't say much except that the mod was disabled prior to the server starting up (which is unusual in it of itself).

**Comment by valkyrienyanko** [comment]
[2022-10-20-2.log](https://github.com/pop4959/Chunky/files/9834735/2022-10-20-2.log)

As a side note the `Mixin transformation of me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl failed` was resolved by removing the mod "MemoryLimitFix". I have not tested using chunky after resolving this error. I just removed chunky and that memory limit fix mod and my modpack works fine now.

**Comment by pop4959** [comment]
It looks like the error is as a result of that crash. Chunky listens to server stop event and expects to have been initialized on startup. I would try it again and see if it works now.

**Comment by valkyrienyanko** [comment]
I won't be trying it again for a while so I'll close this issue for now. I'll let you know if I do try it again.

**Comment by pop4959** [comment]
Alright, sounds good. I would appreciate if you would remove chunky from your incompatibilities list from now since it seems very likely that there isn't any actual incompatibility here.

If you do find issues, feel free to report back either here in an issue or chat with me in the #chunky channel on [Discord](https://discord.gg/ZwVJukcNQG).

**Comment by valkyrienyanko** [comment]
Adding chunky back without the other mod that crashed the modpack works fine. In other words chunky did / does not cause any issues.

**Comment by pop4959** [comment]
Thanks for confirming! Please note that this error should only occur when the server crashes on startup with older versions of Minecraft. This has already been fixed in the latest versions of Chunky.
