### ISSUE TITLE
ChunkyBorder 1.1.50 crash with Minecraft 1.20.2, fabric loader 0.14.22, fabric launcher 0.11.2

### ISSUE THREAD

**Issue by jkonopka** [pop4959/Chunky#293]
I'm seeing a crash in ChunkyBorder 1.1.50 with fabric on Minecraft 1.20.2

running only Chunky 1.3.92, Chunky Border 1.1.50 and fabric api 0.89.3+1.20.2

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-10-06 11:23:11
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_2658.<init>(net.minecraft.class_2960, net.minecraft.class_2540)'
	at org.popcraft.chunkyborder.ChunkyBorderFabric.sendBorderPacket(ChunkyBorderFabric.java:125)
	at org.popcraft.chunkyborder.ChunkyBorderFabric.lambda$onInitialize$0(ChunkyBorderFabric.java:58)
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48)
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:67)
	at net.minecraft.class_3324.handler$zeb000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:2504)
	at net.minecraft.class_3324.method_14570(class_3324.java:195)
	at net.minecraft.class_8610.method_52408(class_8610.java:128)
	at net.minecraft.class_8736.method_53043(class_8736.java:20)
	at net.minecraft.class_8736.method_11054(class_8736.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Linux (amd64) version 4.15.0-163-generic
	Java Version: 17.0.7, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1784093696 bytes (1701 MiB) / 2992635904 bytes (2854 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 72050.14
	Virtual memory used (MB): 89931.44
	Swap memory total (MB): 7632.44
	Swap memory used (MB): 65.00
	JVM Flags: 3 total; -Xmx4096M -Xms256M -XX:ParallelGCThreads=2
	Fabric Mods: 
		chunky: Chunky 1.3.92
		chunkyborder: ChunkyBorder 1.1.50
		fabric-api: Fabric API 0.89.3+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.41+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+d9a2869ba0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.36+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.15+86b12645a0
			fabric-commands-v0: Fabric Commands (v0) 0.2.53+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.72+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.4+285022b3a0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.7+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.2+d19c4129a0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.56+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.25+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.9+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.68+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.32+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.13+f4b7e424a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.26+3bafade3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.2+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.1+e982ae85a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.54+f4b7e424a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.8+b18afef3a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.1+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.5+96509552a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.3+34a3e0e2a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.9+43511215a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.11+86b12645a0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.38+86b12645a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.8+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.14.22
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
	Server Running: true
	Player Count: 0 / 10; []
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by jkonopka** [comment]
oh crap - my mistake - I meant to put issue in a different place - pardon my screw up
