### ISSUE TITLE
Error when loading on 1.20.2 - no paper-plugin.yml or plugin.yml

### ISSUE THREAD

**Issue by matthewm1970** [pop4959/Chunky#295]
Getting the following error when loading Chunky 1.3.92 on a purpur 1.20.2 server:
...
at org.bukkit.craftbukkit.Main.main(Main.java:338) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/Chunky-1.3.92.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:54) ~[purpur-1.20.2.jar:git-Purpur-2086]
...

**Comment by pop4959** [comment]
Sounds like it didn't download correctly or you are using the mod instead of the plugin. Make sure you download the correct version and try again, it should work.
