### ISSUE TITLE
server crashes when trying to run it

### ISSUE THREAD

**Issue by Elmishhh** [pop4959/Chunky#308]
modpack: "create: astral"
version: minecraft forge 1.18.2
if i input my public ipv4 address my server crashes on startup and i get this error:

[18:49:15] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "org.popcraft.chunky.Chunky.disable()" because "this.chunky" is null
        at org.popcraft.chunky.ChunkyFabric.lambda$onInitialize$2(ChunkyFabric.java:42) ~[Chunky-1.2.164.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.1.1+cc71601c60-87d8f812a1297025.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bpi000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:8817) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:565) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:729) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
        
removing chunky returns me with this error instead

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
        at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:569) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:626) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:565) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:729) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by pop4959** [comment]
Hi, it looks like you are trying to run the Fabric mod for Chunky on Forge. Please keep in mind these are separate versions. Make sure you download the correct one.

Also it would not be the cause of your crash given that the server appears to crash without it.

If you still have any questions or need help troubleshooting (regarding chunky specifically) please join us on our [Discord server](https://discord.gg/ZwVJukcNQG).

**Comment by Elmishhh** [comment]
Found the issue
I wasn't supposed to place an IP in server-ip part of my server.properties 

The issue wasn't chunky related at all
