### ISSUE TITLE
ClassNotFoundException: org.popcraft.chunky.shape.ShapeType

### ISSUE THREAD

**Issue by DaisyDogs07** [pop4959/Chunky#313]
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-01-20 10:36:44
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/popcraft/chunky/shape/ShapeType
	at org.popcraft.chunky.command.suggestion.ShapeSuggestionProvider.getSuggestions(ShapeSuggestionProvider.java:24) ~[Chunky-1.3.92.jar!/:?] {re:classloading}
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar!/:?] {}
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:541) ~[brigadier-1.2.9.jar!/:?] {}
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:523) ~[brigadier-1.2.9.jar!/:?] {}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7741_(ServerGamePacketListenerImpl.java:498) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,xf:fml:gottagofast:vehicleMove,xf:fml:gottagofast:playerMove,re:classloading,xf:fml:gottagofast:vehicleMove,xf:fml:gottagofast:playerMove,pl:mixin:APP:forgivingvoid.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.m_5797_(ServerboundCommandSuggestionPacket.java:29) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.m_5797_(ServerboundCommandSuggestionPacket.java:7) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_304213_(PacketUtils.java:24) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:788) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:771) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:765) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:751) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:679) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:256) ~[forge-1.20.4-49.0.21-server.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: org.popcraft.chunky.shape.ShapeType
	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:447) ~[securemodules-2.2.10.jar!/:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 21 more
```

This issue is inconsistent to recreate but it still happens none the less. I've come to open an issue about it in hopes that it will get fixed soon. This is on a Minecraft Forge 49.0.21 Server running on Minecraft 1.20.4 with Chunky version 1.3.92 for Forge 1.20-1.20.4

This crash occurred while the client was fetching autocomplete suggestions when entering the command `/chunky trim ` (with a space after "trim")

Unfortunately I have no other info to give and I hope you will be able to fix this.

**Comment by pop4959** [comment]
This looks like more of a class loader issue than anything. Not sure what I would be able to do about it as you can see in the stack trace this is entirely controlled on Forge's side by their class loader.

I would recommend re-downloading chunky just in case to ensure you don't have a corrupt jar file.

I'll leave this up for a bit in case of other reports, but will probably close sooner than later. Feel free to join the Discord server if you want to troubleshoot more.

**Comment by pop4959** [comment]
Shape type suggestions appear to work just fine on my end using the same version of Forge.

![image](https://github.com/pop4959/Chunky/assets/17698576/1a48c2d3-d57f-491d-bbce-ffa039f176e3)

**Comment by DaisyDogs07** [comment]
Like i said, Its inconsistent to recreate. ive only had this happen twice over the span of a month. so just because you cant recreate it doesnt mean its invalid

**Comment by pop4959** [comment]
> Like i said, Its inconsistent to recreate. ive only had this happen twice over the span of a month. so just because you cant recreate it doesnt mean its invalid

As I said before generally this is not even something that can be addressed on our end even if it is an issue, as the culprit here is essentially the class loader in Forge given the stack trace you've shared. I mean no offense to you personally or deny that this error occurred in your situation, but invalid is the best tag I could choose here given that it is neither really a problem with chunky, nor a bug in chunky.

I do welcome you once again to our [Discord server](https://discord.gg/ZwVJukcNQG) where we can have an open discussion about this. I am more than willing to help you troubleshoot or test this problem, and of course, if it is consistently reproducible and can be traced to chunky this issue can be re-opened.

**Comment by DaisyDogs07** [comment]
Alrighty then, Thanks :)
