### ISSUE TITLE
Failing to load on paper 1.20.6

### ISSUE THREAD

**Issue by Wheretf2** [pop4959/Chunky#342]
When I drop the plugin into my plugins folder and start the server, it fails to load with this output in console
```
[20:43:19 INFO]: [PluginRemapper] Remapping plugin 'plugins/Chunky-1.4.10.jar'...
[20:43:20 INFO]: [PluginRemapper] Done remapping plugin 'plugins/Chunky-1.4.10.jar' in 1060ms.
[20:43:20 ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Chunky-1.4.10.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Chunky-1.4.10.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:81) ~[paper-1.20.6.jar:1.20.6-100-26e90b9]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[paper-1.20.6.jar:1.20.6-100-26e90b9]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.20.6.jar:1.20.6-100-26e90b9]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.20.6.jar:1.20.6-100-26e90b9]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.20.6.jar:1.20.6-100-26e90b9]
        at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.20.6.jar:1.20.6-100-26e90b9]
        at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-100-26e90b9]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Chunky-1.4.10.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
```

I'm running Paper version 1.20.6-100-master@26e90b9
Edit: I'm using [this version of chunky from Modrinth](https://modrinth.com/plugin/chunky/version/ZrmnYk7q)

If there's any other info I can provide please let me know, thank you!

**Comment by pop4959** [comment]
It looks like you downloaded the mod instead of the Bukkit plugin. Download the correct version and you should be fine.

If you have any other questions please feel free to join the [Discord server](https://discord.gg/ZwVJukcNQG).

**Comment by Wheretf2** [comment]
Sorry, totally missed the version

Thanks for your time
Have a good day

**Comment by pop4959** [comment]
No worries, there's a bunch! Totally understandable and it happens all the time.

Glad you found it.
