### ISSUE TITLE
Chunky crashes on server start permission error

### ISSUE THREAD

**Issue by DrBlackross** [pop4959/Chunky#92]
[10:56:54 ERROR]: Could not load 'plugins/Chunky-1.2.54.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.5.jar:git-Paper-607]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.5.jar:git-Paper-607]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-607]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.5.jar:git-Paper-607]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-607]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-607]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.FileNotFoundException: plugins/Chunky-1.2.54.jar (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
        at java.io.RandomAccessFile.open(RandomAccessFile.java:345) ~[?:?]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:214) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1285) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1251) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:247) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:177) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.5.jar:git-Paper-607]

on the linux server 

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

the latest version of paper i have on the box 

paper-1.16.5-607.jar

let me know if i need to post a full debug log

**Comment by DrBlackross** [comment]
oh BTW 

drwxrwxr-x 2 drblackross drblackross    4096 Mar 21 13:38 bStats
-rw-rw---- 1 nobody      nogroup      162956 May 11 10:40 Chunky-1.2.54.jar
drwxrwxr-x 9 drblackross drblackross    4096 May 11 10:41 dynmap
-rw-r--r-- 1 drblackross drblackross 8208222 Feb  8 23:40 Dynmap-3.1-beta7-spigot.jar
-rw-rw-r-- 1 nobody      nogroup     7186761 Apr  5 14:01 inventorypets-2.0.12.jar
drwxrwxr-x 4 drblackross drblackross    4096 May 11 10:57 Minepacks
-rw-rw-r-- 1 drblackross drblackross 1412068 Apr 26 21:51 Minepacks-2.3.22-Release.jar
drwxrwxr-x 4 drblackross drblackross    4096 May 11 10:59 Train_Carts
-rw-rw-r-- 1 nobody      nogroup     2748538 May  8 19:18 TrainCarts-1.16.5-v1-843.jar
drwxrwxr-x 2 drblackross drblackross    4096 Apr 26 21:51 update
drwxrwxr-x 6 drblackross drblackross    4096 Apr  1 14:48 WorldEdit
-rw-rw-r-- 1 nobody      nogroup     4434562 Apr  1 14:47 worldedit-bukkit-7.2.4.jar

**Comment by DrBlackross** [comment]
yep owner:group was the issue with chunky, i need to fix my samba conf on my shared folder
